version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "nightly"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "rustfmt"

[[transformers]]
name = "autopep8"