repos:
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.8
    hooks:
      - id: ripsecrets

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      - id: stylua
